---
# tasks file for backupsrv
- name: Pause for 5 minutes to build app cache
  pause:
    minutes: 5

- name: set timezone to Moscow
  timezone:
    name: Europe/Moscow

- name: Update Repository cache # загружаем репозитории локально
  ansible.builtin.apt:
    update_cache: true

- name: Install # установка postgres и pgadmin, зависимости
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
  with_items:
    - 'borgbackup'
    - 'net-tools'
    - 'wget'
    - 'bash-completion'
    - 'zabbix-agent'
    - 'openssh-server'
    - 'lvm2'
    - 'rsyslog-mysql'

- name: copy fail hosts # копируем hosts для настройки отображения
  copy:
    src: files/hosts
    dest: /etc/hosts 
    
- name: copy fail zabbix_agentd.conf # копируем zabbix_agentd.conf
  copy:
    src: files/zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf   
    
- name: copy fail rsyslog.conf # копируем rsyslog.conf настройка портов
  copy:
    src: files/rsyslog.conf 
    dest: /etc/rsyslog.conf       
    
- name: Add user borg create a password for user borg
  user:
    name: borg  
    password: admin
    
- name: Add the user borg of group
  ansible.builtin.user:
    name: borg
    uid: 1001
    group: borg    
    
- name: Add the user a bash shell
  ansible.builtin.user:
    name: borg
    shell: /bin/bash
    groups: root
    append: yes

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: '/home/borg/.ssh/*'
    state: directory
    owner: borg
    group: borg
    mode: '700'

- name: copy fail authorized_keys  # копируем authorized_keys   
  copy:
    src: files/sshborg/authorized_keys
    dest: /home/borg/.ssh/authorized_keys   

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: '/home/borg/.ssh/authorized_keys'
    owner: borg
    group: borg
    mode: '600'

- name: copy fail authorized_keys  # копируем authorized_keys   
  copy:
    src: files/authorized_keys
    dest: /home/vagrant/.ssh/authorized_keys   

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: '/home/vagrant/.ssh/authorized_keys'
    owner: vagrant
    group: vagrant
    mode: '600'
    
- name: create partition
  parted:
    device: /dev/sdb
    number: 1
    flags: [ lvm ]
    state: present
    part_end: 5GB  
    
- name: Create a volume group on top of /dev/sda1 with physical extent size = 32MB
  community.general.lvg:
    vg: vg_backup
    pvs: /dev/sdb1
    pesize: 4G      
    
- name: task for creating logical volume
  lvol:
    vg: vg_backup
    lv:  lv_backup
    size: 4G
    force: yes 
    
- name: Create directory data1 if does not exist
  file:
    path: '/opt/backup'
    state: directory
    mode: '0755'

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: '/opt/backup'
    state: directory
    owner: borg
    group: borg


- name: format the xfs filesystem
  filesystem:
    fstype: xfs
    dev: /dev/vg_backup/lv_backup

- name: mount the lv on /data1
  mount:
    path: /opt/backup
    src: /dev/vg_backup/lv_backup
    fstype: xfs
    state: mounted      
        
- name: copy fail 50-cloud-init.conf # отключаем вход ssh по паролю
  copy:
    src: files/50-cloud-init.conf  
    dest: /etc/ssh/sshd_config.d/50-cloud-init.conf           

- name: Reload service # Перезапускаем apache
  ansible.builtin.service:
    name: '{{ item }}'
    state: restarted
  with_items:
    - 'zabbix-agent'  
    - 'rsyslog' 

- name: Copy conf netplan
  ansible.builtin.copy:
    src:  files/netplan/
    dest: /etc/netplan/
    directory_mode: yes 
    
- name: Netplan apply
  ansible.builtin.shell:
    cmd: bash -c "sudo netplan apply"  
  ignore_errors: yes        
    
 
 
 
 
 
 
 
 
 
    
    

 
 
 
 
 
 
 
    
    
