---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth1:
      dhcp4: no      
      addresses:
      - 192.168.50.11/24
      gateway4: 192.168.50.15       
      nameservers:
              addresses: 
              - 192.168.50.15
              - 8.8.8.8  
        
