---
# tasks file for zabbix
- name: set timezone to Moscow
  timezone:
    name: Europe/Moscow
    
- name: Download zabbix for ubuntu-20.04 # скачиваем сборку zabbix 6.4
  ansible.builtin.shell:
    cmd: bash -c "sudo wget https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu20.04_all.deb"
    
- name: Unzip zabbix for ubuntu-20.04 # распоковка сборки zabbix 6.4
  ansible.builtin.shell:
    cmd: bash -c "sudo dpkg -i zabbix-release_6.4-1+ubuntu20.04_all.deb"  

- name: Update Repository cache # загружаем репозитории локально
  ansible.builtin.apt:
    update_cache: true
    
- name: install zabbix + components  # установка zabbix  и других компонентов
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - 'zabbix-server-pgsql'
    - 'zabbix-frontend-php'
    - 'php7.4-pgsql'
    - 'zabbix-nginx-conf'
    - 'zabbix-sql-scripts'
    - 'zabbix-agent'
    - 'net-tools'
    - 'traceroute'
    - 'borgbackup'
    - 'openssl'
    - 'rsyslog-mysql'
    - 'bash-completion'
    
- name: copy file zabbix_server.conf # копируем zabbix_server.conf
  copy:
    src: files/zabbix_server.conf
    dest: /etc/zabbix/zabbix_server.conf
    
- name: copy file nginx.conf # копируем nginx.conf
  copy:
    src: files/nginx.conf
    dest: /etc/zabbix/nginx.conf

- name: copy file zabbix.conf.php # копируем zabbix.conf.php
  copy:
    src: files/zabbix.conf.php
    dest: /etc/zabbix/zabbix.conf.php
    
- name: language ru_RU for zabbix # скачиваем русский язык для zabbix 6.4
  ansible.builtin.shell:
    cmd: bash -c "locale-gen ru_RU"

- name: copy fail hosts # копируем hosts для настройки отображения
  copy:
    src: files/hosts
    dest: /etc/hosts

- name: Copy key to backup
  ansible.builtin.copy:
    src:  files/sshborg/
    dest: /root/.ssh/
    directory_mode: yes    
    
- name: Creates directory
  ansible.builtin.file:
    path: /root/.ssh/
    state: directory
    mode: '0700'    
    
- name: Chmod 666
  ansible.builtin.file:
    path: /root/.ssh/id_rsa
    mode: '0600'
 
- name: Chmod 666
  ansible.builtin.file:
    path: /root/.ssh/id_rsa.pub
    mode: '0600'

- name: Chmod 666
  ansible.builtin.file:
    path: /root/.ssh/config
    mode: '0600'    

- name: Copy timer, service to backup
  ansible.builtin.copy:
    src: files/borg-backup.service
    dest: /etc/systemd/system/borg-backup.service
    
- name: Copy timer, service to borg
  ansible.builtin.copy:
    src: files/borg-backup.timer
    dest: /etc/systemd/system/borg-backup.timer     
    
- name: Copy key for https
  ansible.builtin.copy:
    src: files/sslhttps/
    dest: /usr/local/share/ca-certificates/
    directory_mode: yes

- name: install ca package on debian systems
  apt:
    name: ca-certificates
    state: present
    update_cache: yes 

- name: Creates directory
  ansible.builtin.file:
    path: /etc/nginx/certs
    state: directory
    
- name: Copy key for https
  ansible.builtin.copy:
    src: files/sslhttps/zabbix.crt
    dest: /etc/nginx/certs/zabbix.crt
  
- name: Copy key for https
  ansible.builtin.copy:
    src: files/sslhttps/zabbix.key
    dest: /etc/nginx/certs/zabbix.key

- name: Copy conf
  ansible.builtin.copy:
    src: files/zabbix.conf
    dest: /etc/nginx/conf.d/zabbix.conf

- name: copy fail rsyslog # копируем rsyslog
  copy:
    src: files/rsyslog.conf
    dest: /etc/rsyslog.conf

- name: Copy conf netplan
  ansible.builtin.copy:
    src:  files/netplan/
    dest: /etc/netplan/
    directory_mode: yes  

- name: Enable service #Включение сервисов
  ansible.builtin.service:
    name: '{{ item }}'
    enabled: yes
  with_items:
    - 'borg-backup.service'
    - 'borg-backup.timer'
    - 'rsyslog'
    - 'zabbix-server'
    - 'zabbix-agent'
    - 'nginx'
    - 'php7.4-fpm' 

- name: Reload service
  ansible.builtin.service:
    name: '{{ item }}'
    state: restarted
  with_items:
    - 'zabbix-server'
    - 'zabbix-agent'
    - 'nginx'
    - 'php7.4-fpm'
    - 'ssh'
    - 'sshd'
    
- name: Netplan apply
  ansible.builtin.shell:
    cmd: bash -c "sudo netplan apply"  
  ignore_errors: yes
    
    
    
